name: BUILD

on:
  workflow_call:
    inputs:
      target-ref:
        required: true
        type: string
      artefact-ref:
        required: true
        type: string
      feature:
        required: true
        type: string
      site-url:
        required: true
        type: string
    
permissions:
  contents: read
      
jobs:

  # Build static sites
  build-static-site:
    name: 🔨 Build
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment: build

    steps:

      - name: Checkout Soln Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.target-ref }}

      - name: Setup Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: 20
        
      # All static solutions should use package.json and have lint, test, build as commands
      - name: Install
        run: npm install

      # If linting fails will fail this job
      - name: Run linter 
        run: npm run lint

      # If this tests fail the NPM error will fail this job
      - name: Run tests 
        run: |
          npm run test
          echo "### Test Summary" >> $GITHUB_STEP_SUMMARY
          echo "$(npm run test)" >> $GITHUB_STEP_SUMMARY

      - name: 🔨 Run build
        env:
          SITE_URL: ${{ inputs.site-url }}
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artefact-ref }}
          path: 'build'
          retention-days: 1

      - name: Build completed
        run: echo "### Builds Completed :thumbsup:" >> $GITHUB_STEP_SUMMARY